steps:
  - name: system-update
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host_ip
      username: woodpecker
      key:
        from_secret: woodpecker_ssh_key
      script:
        - echo "[$(date '+%Y-%m-%d %H:%M:%S')] > STARTING PACKAGES UPDATE"
        - apt-get update
        - apt-get upgrade -y
	- echo "[$(date '+%Y-%m-%d %H:%M:%S')] > UPDATE FINISHED"
