steps:
  - name: ssh-connection
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host_ip
      username: woodpecker
      key:
        from_secret: woodpecker_ssh_key
      script:
        - echo "Establishing SSH connection..."
	- echo "Listing available upgrades:"
	- apt list --upgradable
