skip_clone: true
steps:
  - name: reboot-system
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host_ip
      username: woodpecker
      key:
        from_secret: woodpecker_ssh_key
      script:
        - echo "[$(date '+%Y-%m-%d %H:%M:%S')] > STARTING SYSTEM REBOOT"
        - sudo reboot
        - uptime
    when:
      - event: cron
        cron: reboot-system 

