name: Remote SSH Command
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: woodpecker
          key: ${{ secrets.KEY }}
          script: |
            whoami
            hostname
